POST http://localhost:5074/api/v1/categories HTTP/1.1
Content-Type: application/json

{
  "name": "Clothing",
  "image": "https://picsum.photos/200/?random=1"
}

###
# Get all categories
GET http://localhost:5074/api/v1/categories HTTP/1.1

###
PATCH  http://localhost:5258/api/v1/categorys/eb469f0a-ca39-4a48-9c27-6c543b4f5b3c HTTP/1.1
Content-Type: application/json

{
  "name": "Beverage",
  "image": "https://picsum.photos/200/?random=1"
}

###
# Get single category by Id
GET http://localhost:5074/api/v1/category/01551c75-520b-4a08-9c6c-3b90755db500 HTTP/1.1
